const { DATA_TYPE } = require("./common");

const EBML_HEADER_ELEMENT_NAME = {
  EBML_VERSION: "EBMLVersion",
  EBML_READ_VERSION: "EBMLReadVersion",
  EBML_MAX_ID_LENGTH: "EBMLMaxIdLength",
  EBML_MAX_SIZE_LENGTH: "EBMLMaxSizeLength",
  DOC_TYPE: "docType",
  DOC_TYPE_VERSION: "docTypeVersion",
  DOC_TYPE_READ_VERSION: "docTypeReadVersion",
};

const EBML_HEADER_ELEMENT_INFO = {
  0x4286: { name: EBML_HEADER_ELEMENT_NAME.EBML_VERSION, type: DATA_TYPE.UNSIGNED_INT },
  0x42f7: { name: EBML_HEADER_ELEMENT_NAME.EBML_READ_VERSION, type: DATA_TYPE.UNSIGNED_INT },
  0x42f2: { name: EBML_HEADER_ELEMENT_NAME.EBML_MAX_ID_LENGTH, type: DATA_TYPE.UNSIGNED_INT },
  0x42f3: { name: EBML_HEADER_ELEMENT_NAME.EBML_MAX_SIZE_LENGTH, type: DATA_TYPE.UNSIGNED_INT },
  0x4282: { name: EBML_HEADER_ELEMENT_NAME.DOC_TYPE, type: DATA_TYPE.STRING },
  0x4287: { name: EBML_HEADER_ELEMENT_NAME.DOC_TYPE_VERSION, type: DATA_TYPE.UNSIGNED_INT },
  0x4285: { name: EBML_HEADER_ELEMENT_NAME.DOC_TYPE_READ_VERSION, type: DATA_TYPE.UNSIGNED_INT },
};

module.exports = { EBML_HEADER_ELEMENT_NAME, EBML_HEADER_ELEMENT_INFO };
