const ERROR_TYPE = {
  LOAD_EBML_ERROR: "LOAD_EBML_ERROR",
  NO_HEADER_ERROR: "NO_HEADER_ERROR",
  PARSE_HEADER_ERROR: "PARSE_HEADER_ERROR",
  PARSE_SEGMENT_ERROR: "PARSE_SEGMENT_ERROR",
  PARSE_SEEKHEAD_ERROR: "PARSE_SEEKHEAD_ERROR",
  PARSE_INFO_ERROR: "PARSE_INFO_ERROR",
  PARSE_TRACKS_ERROR: "PARSE_TRACKS_ERROR",
  PARSE_CUES_ERROR: "PARSE_CUES_ERROR",
  PARSE_CLUSTERS_ERROR: "PARSE_CLUSTERS_ERROR",
  PARSE_SINGLE_CLUSTER_ERROR: "PARSE_SINGLE_CLUSTER_ERROR",
  DATA_INTERFACE_ERROR: "DATA_INTERFACE_ERROR",
  PICK_ELEMENT_ERROR: "PICK_ELEMENT_ERROR",
  SKIP_BYTE_ERROR: "SKIP_BYTE_ERROR",
  JUMP_TO_POSITION_ERROR: "JUMP_TO_POSITION_ERROR",
};

module.exports = { ERROR_TYPE };
